create table if not exists hb_seasons (
    id bigint generated by default as identity primary key,
    name text not null,
    is_active boolean not null default false,
    starts_at timestamptz not null default now(),
    ends_at timestamptz
);

create unique index if not exists hb_one_active_season
    on hb_seasons (is_active)
    where is_active = true;

create table if not exists hb_players (
    id uuid primary key,
    nickname varchar(12) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create table if not exists hb_player_season_stats (
    player_id uuid not null references hb_players(id),
    season_id bigint not null references hb_seasons(id),
    wins integer not null default 0 check (wins >= 0),
    losses integer not null default 0 check (losses >= 0),
    rating integer not null default 1000 check (rating >= 100),
    updated_at timestamptz not null default now(),
    primary key (player_id, season_id)
);

create table if not exists hb_matches (
    match_id uuid primary key,
    room_code varchar(4) not null,
    season_id bigint not null references hb_seasons(id),
    winner_id uuid not null references hb_players(id),
    loser_id uuid not null references hb_players(id),
    reason varchar(20) not null,
    rating_change integer not null,
    created_at timestamptz not null default now(),
    check (winner_id <> loser_id)
);

create table if not exists hb_record_resets (
    id bigint generated by default as identity primary key,
    player_id uuid not null references hb_players(id),
    season_id bigint not null references hb_seasons(id),
    previous_wins integer not null,
    previous_losses integer not null,
    previous_rating integer not null,
    created_at timestamptz not null default now()
);

alter table hb_seasons enable row level security;
alter table hb_players enable row level security;
alter table hb_player_season_stats enable row level security;
alter table hb_matches enable row level security;
alter table hb_record_resets enable row level security;

revoke all on hb_seasons from anon, authenticated;
revoke all on hb_players from anon, authenticated;
revoke all on hb_player_season_stats from anon, authenticated;
revoke all on hb_matches from anon, authenticated;
revoke all on hb_record_resets from anon, authenticated;

insert into hb_seasons (name, is_active)
select '시즌 1', true
where not exists (select 1 from hb_seasons where is_active = true);
