create table if not exists hb_seasons (
    id bigint generated by default as identity primary key,
    name text not null,
    is_active boolean not null default false,
    starts_at timestamptz not null default now(),
    ends_at timestamptz
);

create unique index if not exists hb_one_active_season
    on hb_seasons (is_active)
    where is_active = true;

create table if not exists hb_players (
    id uuid primary key,
    nickname varchar(12) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create table if not exists hb_player_season_stats (
    player_id uuid not null references hb_players(id),
    season_id bigint not null references hb_seasons(id),
    wins integer not null default 0 check (wins >= 0),
    losses integer not null default 0 check (losses >= 0),
    rating integer not null default 1000 check (rating >= 100),
    updated_at timestamptz not null default now(),
    primary key (player_id, season_id)
);

create table if not exists hb_matches (
    match_id uuid primary key,
    room_code varchar(6) not null,
    season_id bigint not null references hb_seasons(id),
    winner_id uuid not null references hb_players(id),
    loser_id uuid not null references hb_players(id),
    reason varchar(20) not null,
    rating_change integer not null,
    created_at timestamptz not null default now(),
    check (winner_id <> loser_id)
);

alter table hb_matches alter column room_code type varchar(6);

create table if not exists hb_record_resets (
    id bigint generated by default as identity primary key,
    player_id uuid not null references hb_players(id),
    season_id bigint not null references hb_seasons(id),
    previous_wins integer not null,
    previous_losses integer not null,
    previous_rating integer not null,
    created_at timestamptz not null default now()
);

create table if not exists hb_push_tokens (
    token text primary key,
    player_id uuid not null references hb_players(id) on delete cascade,
    platform varchar(20) not null default 'android',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists hb_push_tokens_player_idx on hb_push_tokens (player_id);

create table if not exists hb_active_rooms (
    code varchar(6) primary key,
    match_id uuid not null,
    status varchar(20) not null,
    visibility varchar(10) not null default 'public',
    host_id uuid not null references hb_players(id) on delete cascade,
    guest_id uuid references hb_players(id) on delete cascade,
    state jsonb not null,
    expires_at timestamptz not null,
    updated_at timestamptz not null default now()
);

create index if not exists hb_active_rooms_status_idx on hb_active_rooms (status, visibility, expires_at);
create index if not exists hb_active_rooms_host_idx on hb_active_rooms (host_id);
create index if not exists hb_active_rooms_guest_idx on hb_active_rooms (guest_id);

create table if not exists hb_player_presence (
    player_id uuid primary key references hb_players(id) on delete cascade,
    last_seen timestamptz not null default now(),
    available_until timestamptz,
    updated_at timestamptz not null default now()
);

create index if not exists hb_player_presence_seen_idx on hb_player_presence (last_seen desc);
create index if not exists hb_player_presence_available_idx on hb_player_presence (available_until desc);

create table if not exists hb_match_challenges (
    id uuid primary key,
    challenger_id uuid not null references hb_players(id) on delete cascade,
    target_id uuid not null references hb_players(id) on delete cascade,
    status varchar(12) not null default 'pending',
    room_code varchar(6),
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (challenger_id <> target_id),
    check (status in ('pending', 'accepted', 'declined', 'expired', 'cancelled'))
);

create index if not exists hb_match_challenges_challenger_idx on hb_match_challenges (challenger_id, updated_at desc);
create index if not exists hb_match_challenges_target_idx on hb_match_challenges (target_id, updated_at desc);
create index if not exists hb_match_challenges_status_idx on hb_match_challenges (status, expires_at);

alter table hb_seasons enable row level security;
alter table hb_players enable row level security;
alter table hb_player_season_stats enable row level security;
alter table hb_matches enable row level security;
alter table hb_record_resets enable row level security;
alter table hb_push_tokens enable row level security;
alter table hb_active_rooms enable row level security;
alter table hb_player_presence enable row level security;
alter table hb_match_challenges enable row level security;

revoke all on hb_seasons from anon, authenticated;
revoke all on hb_players from anon, authenticated;
revoke all on hb_player_season_stats from anon, authenticated;
revoke all on hb_matches from anon, authenticated;
revoke all on hb_record_resets from anon, authenticated;
revoke all on hb_push_tokens from anon, authenticated;
revoke all on hb_active_rooms from anon, authenticated;
revoke all on hb_player_presence from anon, authenticated;
revoke all on hb_match_challenges from anon, authenticated;

insert into hb_seasons (name, is_active)
select '시즌 1', true
where not exists (select 1 from hb_seasons where is_active = true);
